/**
 * Application Constants
 */

export const MESSAGE_STATUS = {
  PENDING: 'PENDING',
  QUEUED: 'QUEUED',
  SENDING: 'SENDING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  READ: 'READ',
  FAILED: 'FAILED',
};

export const MESSAGE_TYPE = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
  AUDIO: 'AUDIO',
  LOCATION: 'LOCATION',
};

export const SESSION_STATUS = {
  INITIALIZING: 'INITIALIZING',
  WAITING_QR: 'WAITING_QR',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  FAILED: 'FAILED',
  TERMINATED: 'TERMINATED',
};

export const NUMBER_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ACTIVE: 'ACTIVE',
  CONNECTING: 'CONNECTING',
  DISCONNECTED: 'DISCONNECTED',
  BANNED: 'BANNED',
  SUSPENDED: 'SUSPENDED',
  MAINTENANCE: 'MAINTENANCE',
};

export const QUEUE_ACTIONS = {
  CREATE_SESSION: 'create',
  CLOSE_SESSION: 'close',
  RECONNECT_SESSION: 'reconnect',
  HEALTH_CHECK: 'health_check',
  QR_GENERATED: 'qr_generated',
  SESSION_CONNECTED: 'connected',
  SESSION_DISCONNECTED: 'disconnected',
};

export const ERROR_CODES = {
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NOT_CONNECTED: 'SESSION_NOT_CONNECTED',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  INVALID_RECIPIENT: 'INVALID_RECIPIENT',
  BANNED_NUMBER: 'BANNED_NUMBER',
  NETWORK_ERROR: 'NETWORK_ERROR',
};

export const RETRY_CONFIG = {
  MAX_ATTEMPTS: 3,
  INITIAL_DELAY: 1000, // 1 second
  MAX_DELAY: 30000, // 30 seconds
  BACKOFF_MULTIPLIER: 2,
};

export const TIMEOUTS = {
  MESSAGE_SEND: 30000, // 30 seconds
  SESSION_CONNECT: 60000, // 1 minute
  HEALTH_CHECK: 10000, // 10 seconds
  RECONNECT: 5000, // 5 seconds
};

export default {
  MESSAGE_STATUS,
  MESSAGE_TYPE,
  SESSION_STATUS,
  NUMBER_STATUS,
  QUEUE_ACTIONS,
  ERROR_CODES,
  RETRY_CONFIG,
  TIMEOUTS,
};